// <auto-generated />
using FSH.Modules.DNA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable

namespace DNationalSystem.Migrations.PostgreSQL.DNA;

[Microsoft.EntityFrameworkCore.Infrastructure.DbContext(typeof(DnaDbContext))]
[Migration("20260827000000_AddCases")]
public partial class AddCases : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Cases",
            schema: "dna",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                CaseNumber = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                Title = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                Description = table.Column<string>(type: "character varying(4000)", maxLength: 4000, nullable: true),
                Status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                CreatedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                UpdatedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                ClosedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                IsDeleted = table.Column<bool>(type: "boolean", nullable: false),
                DeletedOnUtc = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                DeletedBy = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                TenantId = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Cases", x => x.Id);
            });

        migrationBuilder.CreateIndex(
            name: "IX_Cases_CaseNumber",
            schema: "dna",
            table: "Cases",
            column: "CaseNumber",
            unique: true,
            filter: "\"IsDeleted\" = FALSE");

        migrationBuilder.CreateIndex(
            name: "IX_Cases_IsDeleted",
            schema: "dna",
            table: "Cases",
            column: "IsDeleted");

        migrationBuilder.CreateIndex(
            name: "IX_Cases_TenantId",
            schema: "dna",
            table: "Cases",
            column: "TenantId");

        migrationBuilder.CreateIndex(
            name: "IX_Cases_Status",
            schema: "dna",
            table: "Cases",
            column: "Status");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Cases",
            schema: "dna");
    }
}
