// <auto-generated />
using FSH.Modules.Genetics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DNationalSystem.Migrations.PostgreSQL.Genetics;

[DbContext(typeof(GeneticsDbContext))]
partial class GeneticsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("genetics")
            .HasAnnotation("ProductVersion", "10.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FSH.Modules.Genetics.Domain.GeneticProfile", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<int?>("AnalysisTypeId").HasColumnType("integer");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("ExternalProfileCode").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<bool>("IsReference").HasColumnType("boolean");
            b.Property<Guid>("SampleId").HasColumnType("uuid");
            b.Property<Guid?>("SupersedesProfileId").HasColumnType("uuid");
            b.Property<int>("VersionNumber").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("ExternalProfileCode");
            b.HasIndex("SampleId");
            b.HasIndex("SupersedesProfileId");
            b.HasIndex("SampleId", "VersionNumber");
            b.ToTable("GeneticProfiles", "genetics");
        });

        modelBuilder.Entity("FSH.Modules.Genetics.Domain.ProfileLocus", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid>("GeneticProfileId").HasColumnType("uuid");
            b.Property<string>("Marker").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.HasKey("Id");
            b.HasIndex("GeneticProfileId");
            b.HasIndex("GeneticProfileId", "Marker").IsUnique();
            b.ToTable("ProfileLoci", "genetics");
        });

        modelBuilder.Entity("FSH.Modules.Genetics.Domain.AlleleCall", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid>("ProfileLocusId").HasColumnType("uuid");
            b.Property<int>("SortOrder").HasColumnType("integer");
            b.Property<string>("Value").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.HasKey("Id");
            b.HasIndex("ProfileLocusId");
            b.ToTable("AlleleCalls", "genetics");
        });

        modelBuilder.Entity("FSH.Modules.Genetics.Domain.PeakObservation", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("AlleleValue").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("Channel").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<double?>("HeightRfu").HasColumnType("double precision");
            b.Property<Guid>("ProfileLocusId").HasColumnType("uuid");
            b.Property<double?>("SizeBp").HasColumnType("double precision");
            b.Property<int>("SortOrder").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("ProfileLocusId");
            b.ToTable("PeakObservations", "genetics");
        });

        modelBuilder.Entity("FSH.Modules.Genetics.Domain.AlleleCall", b =>
        {
            b.HasOne("FSH.Modules.Genetics.Domain.ProfileLocus", null)
                .WithMany()
                .HasForeignKey("ProfileLocusId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("FSH.Modules.Genetics.Domain.PeakObservation", b =>
        {
            b.HasOne("FSH.Modules.Genetics.Domain.ProfileLocus", null)
                .WithMany()
                .HasForeignKey("ProfileLocusId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("FSH.Modules.Genetics.Domain.ProfileLocus", b =>
        {
            b.HasOne("FSH.Modules.Genetics.Domain.GeneticProfile", null)
                .WithMany()
                .HasForeignKey("GeneticProfileId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
