<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FSH.Modules.ScientificAnalysis</RootNamespace>
    <AssemblyName>FSH.Modules.ScientificAnalysis</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
    <ProjectReference Include="..\Modules.ScientificAnalysis.Contracts\Modules.ScientificAnalysis.Contracts.csproj" />
  </ItemGroup>
</Project>