// <auto-generated />
using FSH.Modules.Evidence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DNationalSystem.Migrations.PostgreSQL.Evidence;

[DbContext(typeof(EvidenceDbContext))]
partial class EvidenceDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("evidence")
            .HasAnnotation("ProductVersion", "10.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FSH.Modules.Evidence.Domain.EvidenceItem", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid>("CaseId").HasColumnType("uuid");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Description").HasMaxLength(4096).HasColumnType("character varying(4096)");
            b.Property<string>("ExternalReference").HasMaxLength(128).HasColumnType("character varying(128)");
            b.HasKey("Id");
            b.HasIndex("CaseId");
            b.HasIndex("ExternalReference");
            b.ToTable("EvidenceItems", "evidence");
        });
#pragma warning restore 612, 618
    }
}
