<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FSH.Modules.Matching.Contracts</RootNamespace>
    <AssemblyName>FSH.Modules.Matching.Contracts</AssemblyName>
    <NoWarn>$(NoWarn);S2094</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
  </ItemGroup>
</Project>