<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FSH.Modules.Genetics</RootNamespace>
    <AssemblyName>FSH.Modules.Genetics</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
    <ProjectReference Include="..\Modules.Genetics.Contracts\Modules.Genetics.Contracts.csproj" />
    <ProjectReference Include="..\..\Samples\Modules.Samples.Contracts\Modules.Samples.Contracts.csproj" />
  </ItemGroup>
</Project>