<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Modules.Cases.Contracts</RootNamespace>
		<AssemblyName>FSH.Modules.Cases.Contracts</AssemblyName>
		<NoWarn>$(NoWarn);S2094</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
	</ItemGroup>

</Project>