// <auto-generated />
using FSH.Modules.Samples.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DNationalSystem.Migrations.PostgreSQL.Samples;

[DbContext(typeof(SamplesDbContext))]
partial class SamplesDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("samples")
            .HasAnnotation("ProductVersion", "10.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FSH.Modules.Samples.Domain.BiologicalSample", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime?>("CollectedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("CollectionNote").HasMaxLength(4096).HasColumnType("character varying(4096)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid>("EvidenceItemId").HasColumnType("uuid");
            b.Property<string>("ExternalSampleCode").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<Guid?>("ParentSampleId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("EvidenceItemId");
            b.HasIndex("ExternalSampleCode");
            b.HasIndex("ParentSampleId");
            b.ToTable("BiologicalSamples", "samples");
        });
#pragma warning restore 612, 618
    }
}
