// <auto-generated />
using FSH.Modules.ScientificAnalysis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DNationalSystem.Migrations.PostgreSQL.ScientificAnalysis;

[DbContext(typeof(ScientificAnalysisDbContext))]
partial class ScientificAnalysisDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("scientific_analysis")
            .HasAnnotation("ProductVersion", "10.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FSH.Modules.ScientificAnalysis.Domain.AnalysisRun", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("AlgorithmId").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTime>("CompletedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("EngineName").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<int?>("EngineHttpStatusCode").HasColumnType("integer");
            b.Property<string>("EngineVersion").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<Guid>("InitiatedByUserId").HasColumnType("uuid");
            b.Property<string>("Outcome").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<string>("RequestJson").IsRequired().HasColumnType("text");
            b.Property<string>("RequestSha256").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("ResponseJson").HasColumnType("text");
            b.Property<string>("ResponseSha256").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTime>("StartedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("UpstreamCommit").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.HasKey("Id");
            b.HasIndex("AlgorithmId");
            b.HasIndex("InitiatedByUserId");
            b.HasIndex("StartedAtUtc");
            b.ToTable("AnalysisRuns", "scientific_analysis");
        });
#pragma warning restore 612, 618
    }
}
